- name: Install and setup Jellyfin
  when: jellyfin_enabled is true
  block:
    - name: Create Jellyfin Docker directory
      ansible.builtin.file:
        path: "{{ jellyfin_root }}"
        mode: "0755"
        state: directory
        group: "{{ server_group }}"
        owner: "{{ server_user }}"

    - name: Download the latest container image
      # Available Docker container images
      # https://hub.docker.com/r/jellyfin/jellyfin/tags
      ansible.builtin.command: docker pull jellyfin/jellyfin:latest
      register: pull_result
      changed_when: "'Image is up to date for jellyfin/jellyfin' not in pull_result.stdout"

    - name: Create persistent storage for configuration and cache data
      ansible.builtin.file:
        path: "{{ item }}"
        mode: "0755"
        state: directory
        group: "{{ server_group }}"
        owner: "{{ server_user }}"
      with_items:
        - "{{ jellyfin_cache_directory }}"
        - "{{ jellyfin_config_directory }}"

    - name: Create Jellyfin Docker compose file
      ansible.builtin.template:
        src: ../files/docker_compose_template.j2
        dest: "{{ jellyfin_root }}/docker-compose.yml"
        mode: "0644"
        group: "{{ server_group }}"
        owner: "{{ server_user }}"

- name: Start or restart Jellyfin
  when: jellyfin_enabled is true
  block:
    - name: Start or restart Jellyfin Docker container
      ansible.builtin.command: docker compose up --detach
      args:
        chdir: "{{ jellyfin_root }}"
      register: start_jellyfin
      changed_when: start_jellyfin.rc == 0

- name: Stop Jellyfin
  when: jellyfin_enabled is false
  block:
    - name: Stop Jellyfin Docker container
      ansible.builtin.command: docker compose down
      args:
        chdir: "{{ jellyfin_root }}"
      register: stop_jellyfin
      changed_when: stop_jellyfin.rc == 0
