- name: Setup Ansible NAS
  hosts: nas

  roles:
    ### -------------------------------
    ### Requirements
    ### -------------------------------
    - role: docker
      tags:
        - docker

    - role: tailscale
      tags:
        - tailscale
