- name: Setup Ansible NAS
  hosts: nas

  roles:
    ### -------------------------------
    ### Requirements
    ### -------------------------------
    - role: ansible-general
      tags:
        - ansible-general

    - role: docker
      tags:
        - docker

    - role: tailscale
      tags:
        - tailscale

    - role: samba
      tags:
        - samba

    ### -------------------------------
    ### Applications
    ### -------------------------------
    - role: jellyfin
      tags:
        - jellyfin

    - role: immich
      tags:
        - immich

    - role: traefik
      tags:
        - traefik
