- name: Setup Ansible NAS
  hosts: nas

  roles:
    ### -------------------------------
    ### Requirements
    ### -------------------------------
    - role: ansible_general
      tags:
        - ansible_general

    - role: monitoring
      tags:
        - monitoring

    - role: docker
      tags:
        - docker

    - role: watchtower
      tags:
        - watchtower

    - role: tailscale
      tags:
        - tailscale

    - role: traefik
      tags:
        - traefik

    - role: samba
      tags:
        - samba

    ### -------------------------------
    ### Applications
    ### -------------------------------
    - role: jellyfin
      tags:
        - jellyfin

    - role: immich
      tags:
        - immich

    - role: ytdl_sub
      tags:
        - ytdl_sub
