- name: Setup Ansible NAS
  hosts: nas

  roles:
    ### -------------------------------
    ### Requirements
    ### -------------------------------
    - role: ansible-general
      tags:
        - ansible-general

    - role: nginx
      tags:
        - nginx

    - role: docker
      tags:
        - docker

    - role: tailscale
      tags:
        - tailscale

    - role: samba
      tags:
        - samba
