- name: Setup Monitoring Raspberry Pi
  hosts: otel

  roles:
    ### -------------------------------
    ### Requirements
    ### -------------------------------
    - role: docker_pi
      tags:
        - docker_pi

    ### -------------------------------
    ### Applications
    ### -------------------------------
    - role: grafana
      tags:
        - grafana

    - role: uptime_kuma
      tags:
        - uptime_kuma
