- name: Setup Monitoring Raspberry Pi
  hosts: otel

  roles:
    ### -------------------------------
    ### Requirements
    ### -------------------------------
    - role: docker-pi
      tags:
        - docker-pi

    ### -------------------------------
    ### Applications
    ### -------------------------------
    - role: grafana
      tags:
        - grafana
