- name: Install and setup Watchtower
  block:
    - name: Create Watchtower Docker directory
      ansible.builtin.file:
        path: "{{ watchtower_root }}"
        mode: "0755"
        state: directory
        group: "{{ server_group }}"
        owner: "{{ server_user }}"

    - name: Create Watcher Docker compose file
      ansible.builtin.template:
        src: ../files/docker_compose_template.j2
        dest: "{{ watchtower_root }}/docker-compose.yml"
        mode: "0644"
        group: "{{ server_group }}"
        owner: "{{ server_user }}"

- name: Get Watchtower container status
  ansible.builtin.command: docker container ls --filter name=watchtower
  register: watchtower_container_status_result
  changed_when: false
  check_mode: false

- name: Start or restart Watchtower
  block:
    - name: Start Watchtower Docker container
      when: watchtower_container_status_result.stdout.find('watchtower') == -1
      ansible.builtin.command: docker compose up --detach
      args:
        chdir: "{{ watchtower_root }}"
      register: start_watchtower
      changed_when: start_watchtower.rc == 0

    - name: Restart Watchtower Docker container
      when: watchtower_container_status_result.stdout.find('Up') != -1
      ansible.builtin.command: docker compose restart
      args:
        chdir: "{{ watchtower_root }}"
      register: restart_watchtower
      changed_when: restart_watchtower.rc == 0

- name: Stop Watchtower
  when: watchtower_enabled is false
  block:
    - name: Stop Watchtower Docker container
      when: watchtower_container_status_result.stdout.find('Up') != -1
      ansible.builtin.command: docker compose down
      args:
        chdir: "{{ watchtower_root }}"
      register: stop_watchtower
      changed_when: stop_watchtower.rc == 0
