- name: Install and setup Watchtower
  block:
    - name: Create Watchtower Docker directory
      ansible.builtin.file:
        path: "{{ watchtower_root }}"
        mode: "0755"
        state: directory
        group: "{{ server_group }}"
        owner: "{{ server_user }}"

    - name: Create Watcher Docker compose file
      ansible.builtin.template:
        src: ../files/docker_compose_template.j2
        dest: "{{ watchtower_root }}/docker-compose.yml"
        mode: "0644"
        group: "{{ server_group }}"
        owner: "{{ server_user }}"

- name: Start or restart Watchtower
  block:
    - name: Start or restart Watchtower Docker container
      ansible.builtin.command: docker compose up --detach
      args:
        chdir: "{{ watchtower_root }}"
      register: start_watchtower
      changed_when: start_watchtower.rc == 0

- name: Stop Watchtower
  when: watchtower_enabled is false
  block:
    - name: Stop Watchtower Docker container
      ansible.builtin.command: docker compose down
      args:
        chdir: "{{ watchtower_root }}"
      register: stop_watchtower
      changed_when: stop_watchtower.rc == 0
