- name: Install and setup Immich
  when: immich_enabled is true
  block:
    - name: Create directories for upload location and DB data
      ansible.builtin.file:
        path: "{{ item }}"
        mode: "0755"
        state: directory
        group: "{{ server_group }}"
        owner: "{{ server_user }}"
      with_items:
        - "{{ immich_upload_location }}"
        - "{{ immich_db_data_location }}"

    - name: Create Immich Docker compose file
      ansible.builtin.template:
        src: ../files/docker_compose_template.j2
        dest: "{{ immich_root }}/docker-compose.yml"
        mode: "0644"
        group: "{{ server_group }}"
        owner: "{{ server_user }}"

    - name: Create Immich .env file
      ansible.builtin.template:
        src: ../files/env_template.j2
        dest: "{{ immich_root }}/.env"
        mode: "0644"
        group: "{{ server_group }}"
        owner: "{{ server_user }}"

- name: Start or restart Immich
  when: immich_enabled is true
  block:
    - name: Start or restart Immich Docker container
      ansible.builtin.command: docker compose up --detach
      args:
        chdir: "{{ immich_root }}"
      register: start_immich
      changed_when: start_immich.rc == 0

- name: Stop Immich
  when: immich_enabled is false
  block:
    - name: Stop Immich Docker container
      ansible.builtin.command: docker compose down
      args:
        chdir: "{{ immich_root }}"
      register: stop_immich
      changed_when: stop_immich.rc == 0
