- name: Install and setup Immich
  when: immich_enabled is true
  block:
    - name: Create directories for upload location and DB data
      ansible.builtin.file:
        path: "{{ item }}"
        mode: "0755"
        state: directory
      with_items:
        - "{{ immich_upload_location }}"
        - "{{ immich_db_data_location }}"

    - name: Create Immich Docker compose file
      ansible.builtin.template:
        src: ../files/docker_compose_template.j2
        dest: "{{ immich_root }}/docker-compose.yml"
        mode: "0644"

    - name: Create Immich .env file
      ansible.builtin.template:
        src: ../files/env_template.j2
        dest: "{{ immich_root }}/.env"
        mode: "0644"

- name: Get Immich container status
  ansible.builtin.command: docker container ls --filter name=immich
  register: immich_container_status_result
  changed_when: false
  check_mode: false

- name: Start or restart Immich
  when: immich_enabled is true
  block:
    - name: Start Immich Docker container
      when: immich_container_status_result.stdout.find('immich') == -1
      ansible.builtin.command: docker compose up --detach
      args:
        chdir: "{{ immich_root }}"
      register: start_immich
      changed_when: start_immich.rc == 0

    - name: Restart Immich Docker container
      when: immich_container_status_result.stdout.find('Up') != -1
      ansible.builtin.command: docker compose restart
      args:
        chdir: "{{ immich_root }}"
      register: restart_immich
      changed_when: restart_immich.rc == 0

- name: Stop Immich
  when: immich_enabled is false
  block:
    - name: Stop Immich Docker container
      when: immich_container_status_result.stdout.find('Up') != -1
      ansible.builtin.command: docker compose down
      args:
        chdir: "{{ immich_root }}"
      register: stop_immich
      changed_when: stop_immich.rc == 0
