- name: Install and setup Uptime Kuma
  when: uptime_kuma_enabled is true
  block:
    - name: Create Uptime Kuma Docker directory
      ansible.builtin.file:
        path: "{{ uptime_kuma_root }}"
        mode: "0755"
        state: directory

    - name: Create Uptime Kuma Docker compose file
      ansible.builtin.template:
        src: ../files/docker_compose_template.j2
        dest: "{{ uptime_kuma_root }}/docker-compose.yml"
        mode: "0644"

- name: Start or restart Uptime Kuma
  when: uptime_kuma_enabled is true
  block:
    - name: Start or restart Uptime Kuma Docker container
      ansible.builtin.command: docker compose up --detach
      args:
        chdir: "{{ uptime_kuma_root }}"
      register: start_uptime_kuma
      changed_when: start_uptime_kuma.rc == 0

- name: Stop Uptime Kuma
  when: uptime_kuma_enabled is false
  block:
    - name: Stop Uptime Kuma Docker container
      ansible.builtin.command: docker compose down
      args:
        chdir: "{{ uptime_kuma_root }}"
      register: stop_uptime_kuma
      changed_when: stop_uptime_kuma.rc == 0
