- name: Install and setup ytdl-sub
  when: ytdl_sub_enabled is true
  block:
    - name: Create directories for config and data
      ansible.builtin.file:
        path: "{{ item }}"
        mode: "0755"
        state: directory
        group: "{{ server_group }}"
        owner: "{{ server_user }}"
      with_items:
        - "{{ ytdl_sub_config_directory }}"
        - "{{ ytdl_sub_youtube_root }}"

    - name: Create ytdl-sub Docker compose file
      ansible.builtin.template:
        src: ../files/docker_compose_template.j2
        dest: "{{ ytdl_sub_root }}/docker-compose.yml"
        mode: "0644"
        group: "{{ server_group }}"
        owner: "{{ server_user }}"

- name: Start or restart ytdl-sub
  when: ytdl_sub_enabled is true
  block:
    - name: Start or restart ytdl-sub Docker container
      ansible.builtin.command: docker compose up --detach
      args:
        chdir: "{{ ytdl_sub_root }}"
      register: start_ytdl_sub
      changed_when: start_ytdl_sub.rc == 0

- name: Stop ytdl-sub
  when: ytdl_sub_enabled is false
  block:
    - name: Stop ytdl-sub Docker container
      ansible.builtin.command: docker compose down
      args:
        chdir: "{{ ytdl_sub_root }}"
      register: stop_ytdl_sub
      changed_when: stop_ytdl_sub.rc == 0
