- name: Install and setup Traefik
  when: traefik_enabled is true
  block:
    - name: Create Traefik Docker directory
      ansible.builtin.file:
        path: "{{ traefik_root }}"
        mode: "0755"
        state: directory

    - name: Download the latest container image
      ansible.builtin.command: docker pull traefik:v3.3
      register: pull_result
      changed_when: "'Image is up to date' not in pull_result.stdout"

    - name: Create persistent storage for configuration data
      ansible.builtin.file:
        path: "{{ item }}"
        mode: "0755"
        state: directory
      with_items:
        - "{{ traefik_config_directory }}"

    - name: Create Traefik Docker compose file
      ansible.builtin.template:
        src: ../files/docker_compose_template.j2
        dest: "{{ traefik_root }}/docker-compose.yml"
        mode: "0644"

    # Needed because this issue exists in the version of Traefik currently used
    # https://github.com/traefik/traefik/issues/8753
    - name: Create Traefik custom config
      ansible.builtin.template:
        src: ../files/dynamic_conf_template.j2
        dest: "{{ traefik_config_directory }}/dynamic_conf.yml"
        mode: "0644"

    - name: Create Traefik environment vars file
      ansible.builtin.template:
        src: ../files/env_template.j2
        dest: "{{ traefik_root }}/.env"
        mode: "0644"

- name: Start Traefik
  when: traefik_enabled is true
  block:
    - name: Get Traefik container status
      ansible.builtin.command: docker container ls --filter name=traefik
      register: traefik_container_status_result
      changed_when: false
      check_mode: false

    - name: Start Traefik Docker container
      when: traefik_container_status_result.stdout.find('traefik') == -1
      ansible.builtin.command: docker compose up --detach
      args:
        chdir: "{{ traefik_root }}"
      register: start_traefik
      changed_when: start_traefik.stdout.find("Container traefik  Started") != -1 or start_traefik.stdout.find("Container traefik  Starting") != -1
