- name: Install and setup Traefik
  when: traefik_enabled is true
  block:
    - name: Create Traefik Docker directory
      ansible.builtin.file:
        path: "{{ traefik_root }}"
        mode: "0755"
        state: directory

    - name: Download the latest container image
      ansible.builtin.command: docker pull traefik:v3.3
      register: pull_result
      changed_when: "'Image is up to date' not in pull_result.stdout"

    - name: Create Traefik Docker compose file
      ansible.builtin.template:
        src: ../files/docker_compose_template.j2
        dest: "{{ traefik_root }}/docker-compose.yml"
        mode: "0644"

- name: Start Traefik
  when: traefik_enabled is true
  block:
    - name: Get Traefik container status
      ansible.builtin.command: docker container ls --filter name=traefik
      register: traefik_container_status_result
      changed_when: false
      check_mode: false

    - name: Start Traefik Docker container
      when: traefik_container_status_result.stdout.find('traefik') == -1
      ansible.builtin.command: docker compose up --detach
      args:
        chdir: "{{ traefik_root }}"
      register: start_traefik
      changed_when: start_traefik.stdout.find("Container traefik  Started") != -1 or start_traefik.stdout.find("Container traefik  Starting") != -1
